# -*- coding: utf-8 -*-
"""DeleteAndEarn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1biFlOWmbItuo83d0_Y9UeP2ET5FaAbLL
"""

class Solution:
    def deleteAndEarn(self, nums: List[int]) -> int:
        if(nums is None or len(nums)==0): return 0
        
        max_int = 0
        for num in nums:
            max_int = max(max_int, num)
        dp = [0]*(max_int+1)
        for i in range(len(nums)):
            idx = nums[i]
            dp[idx] = dp[idx] + nums[i]
            
        skip = 0
        take = dp[0]
        
        for i in range(len(dp)):
            temp = skip
            skip = max(skip, take)
            take = temp + dp[i]
        return max(skip, take)